#!/usr/bin/env ruby
#
# Copyright 2008-2010 Amazon.com, Inc. or its affiliates.  All Rights Reserved.

if File.symlink? __FILE__
  $LOAD_PATH.unshift File.dirname(File.readlink(__FILE__))
else
  $LOAD_PATH.unshift File.dirname(__FILE__)
end
require 'elastic-mapreduce-cli'
